language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hedzde/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true hedzde/docker-react yarn run test
#Will fail. EleasticBean app is deleted => No -> "docker-react" No -> "DockerReact-env" on AWS.
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-054896547188"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY